// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package grpc.shop.proto;

public interface ReplyShopListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shop.ReplyShopList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  java.util.List<grpc.shop.proto.ReplyShop> 
      getReplyShopListList();
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  grpc.shop.proto.ReplyShop getReplyShopList(int index);
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  int getReplyShopListCount();
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  java.util.List<? extends grpc.shop.proto.ReplyShopOrBuilder> 
      getReplyShopListOrBuilderList();
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  grpc.shop.proto.ReplyShopOrBuilder getReplyShopListOrBuilder(
      int index);
}
