// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package grpc.shop.proto;

/**
 * Protobuf type {@code shop.ReplyShopList}
 */
public  final class ReplyShopList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:shop.ReplyShopList)
    ReplyShopListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplyShopList.newBuilder() to construct.
  private ReplyShopList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplyShopList() {
    replyShopList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplyShopList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              replyShopList_ = new java.util.ArrayList<grpc.shop.proto.ReplyShop>();
              mutable_bitField0_ |= 0x00000001;
            }
            replyShopList_.add(
                input.readMessage(grpc.shop.proto.ReplyShop.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        replyShopList_ = java.util.Collections.unmodifiableList(replyShopList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.shop.proto.ShopProto.internal_static_shop_ReplyShopList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.shop.proto.ShopProto.internal_static_shop_ReplyShopList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.shop.proto.ReplyShopList.class, grpc.shop.proto.ReplyShopList.Builder.class);
  }

  public static final int REPLYSHOPLIST_FIELD_NUMBER = 1;
  private java.util.List<grpc.shop.proto.ReplyShop> replyShopList_;
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  public java.util.List<grpc.shop.proto.ReplyShop> getReplyShopListList() {
    return replyShopList_;
  }
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  public java.util.List<? extends grpc.shop.proto.ReplyShopOrBuilder> 
      getReplyShopListOrBuilderList() {
    return replyShopList_;
  }
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  public int getReplyShopListCount() {
    return replyShopList_.size();
  }
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  public grpc.shop.proto.ReplyShop getReplyShopList(int index) {
    return replyShopList_.get(index);
  }
  /**
   * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
   */
  public grpc.shop.proto.ReplyShopOrBuilder getReplyShopListOrBuilder(
      int index) {
    return replyShopList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < replyShopList_.size(); i++) {
      output.writeMessage(1, replyShopList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < replyShopList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, replyShopList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.shop.proto.ReplyShopList)) {
      return super.equals(obj);
    }
    grpc.shop.proto.ReplyShopList other = (grpc.shop.proto.ReplyShopList) obj;

    boolean result = true;
    result = result && getReplyShopListList()
        .equals(other.getReplyShopListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getReplyShopListCount() > 0) {
      hash = (37 * hash) + REPLYSHOPLIST_FIELD_NUMBER;
      hash = (53 * hash) + getReplyShopListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.shop.proto.ReplyShopList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.shop.proto.ReplyShopList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.shop.proto.ReplyShopList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.shop.proto.ReplyShopList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.shop.proto.ReplyShopList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shop.ReplyShopList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shop.ReplyShopList)
      grpc.shop.proto.ReplyShopListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.shop.proto.ShopProto.internal_static_shop_ReplyShopList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.shop.proto.ShopProto.internal_static_shop_ReplyShopList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.shop.proto.ReplyShopList.class, grpc.shop.proto.ReplyShopList.Builder.class);
    }

    // Construct using grpc.shop.proto.ReplyShopList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReplyShopListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (replyShopListBuilder_ == null) {
        replyShopList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        replyShopListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.shop.proto.ShopProto.internal_static_shop_ReplyShopList_descriptor;
    }

    public grpc.shop.proto.ReplyShopList getDefaultInstanceForType() {
      return grpc.shop.proto.ReplyShopList.getDefaultInstance();
    }

    public grpc.shop.proto.ReplyShopList build() {
      grpc.shop.proto.ReplyShopList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.shop.proto.ReplyShopList buildPartial() {
      grpc.shop.proto.ReplyShopList result = new grpc.shop.proto.ReplyShopList(this);
      int from_bitField0_ = bitField0_;
      if (replyShopListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          replyShopList_ = java.util.Collections.unmodifiableList(replyShopList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.replyShopList_ = replyShopList_;
      } else {
        result.replyShopList_ = replyShopListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.shop.proto.ReplyShopList) {
        return mergeFrom((grpc.shop.proto.ReplyShopList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.shop.proto.ReplyShopList other) {
      if (other == grpc.shop.proto.ReplyShopList.getDefaultInstance()) return this;
      if (replyShopListBuilder_ == null) {
        if (!other.replyShopList_.isEmpty()) {
          if (replyShopList_.isEmpty()) {
            replyShopList_ = other.replyShopList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReplyShopListIsMutable();
            replyShopList_.addAll(other.replyShopList_);
          }
          onChanged();
        }
      } else {
        if (!other.replyShopList_.isEmpty()) {
          if (replyShopListBuilder_.isEmpty()) {
            replyShopListBuilder_.dispose();
            replyShopListBuilder_ = null;
            replyShopList_ = other.replyShopList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            replyShopListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReplyShopListFieldBuilder() : null;
          } else {
            replyShopListBuilder_.addAllMessages(other.replyShopList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.shop.proto.ReplyShopList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.shop.proto.ReplyShopList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.shop.proto.ReplyShop> replyShopList_ =
      java.util.Collections.emptyList();
    private void ensureReplyShopListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        replyShopList_ = new java.util.ArrayList<grpc.shop.proto.ReplyShop>(replyShopList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.shop.proto.ReplyShop, grpc.shop.proto.ReplyShop.Builder, grpc.shop.proto.ReplyShopOrBuilder> replyShopListBuilder_;

    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public java.util.List<grpc.shop.proto.ReplyShop> getReplyShopListList() {
      if (replyShopListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(replyShopList_);
      } else {
        return replyShopListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public int getReplyShopListCount() {
      if (replyShopListBuilder_ == null) {
        return replyShopList_.size();
      } else {
        return replyShopListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public grpc.shop.proto.ReplyShop getReplyShopList(int index) {
      if (replyShopListBuilder_ == null) {
        return replyShopList_.get(index);
      } else {
        return replyShopListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder setReplyShopList(
        int index, grpc.shop.proto.ReplyShop value) {
      if (replyShopListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyShopListIsMutable();
        replyShopList_.set(index, value);
        onChanged();
      } else {
        replyShopListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder setReplyShopList(
        int index, grpc.shop.proto.ReplyShop.Builder builderForValue) {
      if (replyShopListBuilder_ == null) {
        ensureReplyShopListIsMutable();
        replyShopList_.set(index, builderForValue.build());
        onChanged();
      } else {
        replyShopListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder addReplyShopList(grpc.shop.proto.ReplyShop value) {
      if (replyShopListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyShopListIsMutable();
        replyShopList_.add(value);
        onChanged();
      } else {
        replyShopListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder addReplyShopList(
        int index, grpc.shop.proto.ReplyShop value) {
      if (replyShopListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReplyShopListIsMutable();
        replyShopList_.add(index, value);
        onChanged();
      } else {
        replyShopListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder addReplyShopList(
        grpc.shop.proto.ReplyShop.Builder builderForValue) {
      if (replyShopListBuilder_ == null) {
        ensureReplyShopListIsMutable();
        replyShopList_.add(builderForValue.build());
        onChanged();
      } else {
        replyShopListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder addReplyShopList(
        int index, grpc.shop.proto.ReplyShop.Builder builderForValue) {
      if (replyShopListBuilder_ == null) {
        ensureReplyShopListIsMutable();
        replyShopList_.add(index, builderForValue.build());
        onChanged();
      } else {
        replyShopListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder addAllReplyShopList(
        java.lang.Iterable<? extends grpc.shop.proto.ReplyShop> values) {
      if (replyShopListBuilder_ == null) {
        ensureReplyShopListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, replyShopList_);
        onChanged();
      } else {
        replyShopListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder clearReplyShopList() {
      if (replyShopListBuilder_ == null) {
        replyShopList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        replyShopListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public Builder removeReplyShopList(int index) {
      if (replyShopListBuilder_ == null) {
        ensureReplyShopListIsMutable();
        replyShopList_.remove(index);
        onChanged();
      } else {
        replyShopListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public grpc.shop.proto.ReplyShop.Builder getReplyShopListBuilder(
        int index) {
      return getReplyShopListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public grpc.shop.proto.ReplyShopOrBuilder getReplyShopListOrBuilder(
        int index) {
      if (replyShopListBuilder_ == null) {
        return replyShopList_.get(index);  } else {
        return replyShopListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public java.util.List<? extends grpc.shop.proto.ReplyShopOrBuilder> 
         getReplyShopListOrBuilderList() {
      if (replyShopListBuilder_ != null) {
        return replyShopListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(replyShopList_);
      }
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public grpc.shop.proto.ReplyShop.Builder addReplyShopListBuilder() {
      return getReplyShopListFieldBuilder().addBuilder(
          grpc.shop.proto.ReplyShop.getDefaultInstance());
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public grpc.shop.proto.ReplyShop.Builder addReplyShopListBuilder(
        int index) {
      return getReplyShopListFieldBuilder().addBuilder(
          index, grpc.shop.proto.ReplyShop.getDefaultInstance());
    }
    /**
     * <code>repeated .shop.ReplyShop replyShopList = 1;</code>
     */
    public java.util.List<grpc.shop.proto.ReplyShop.Builder> 
         getReplyShopListBuilderList() {
      return getReplyShopListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.shop.proto.ReplyShop, grpc.shop.proto.ReplyShop.Builder, grpc.shop.proto.ReplyShopOrBuilder> 
        getReplyShopListFieldBuilder() {
      if (replyShopListBuilder_ == null) {
        replyShopListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.shop.proto.ReplyShop, grpc.shop.proto.ReplyShop.Builder, grpc.shop.proto.ReplyShopOrBuilder>(
                replyShopList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        replyShopList_ = null;
      }
      return replyShopListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:shop.ReplyShopList)
  }

  // @@protoc_insertion_point(class_scope:shop.ReplyShopList)
  private static final grpc.shop.proto.ReplyShopList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.shop.proto.ReplyShopList();
  }

  public static grpc.shop.proto.ReplyShopList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplyShopList>
      PARSER = new com.google.protobuf.AbstractParser<ReplyShopList>() {
    public ReplyShopList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplyShopList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplyShopList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplyShopList> getParserForType() {
    return PARSER;
  }

  public grpc.shop.proto.ReplyShopList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

