// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package grpc.shop.proto;

public interface ReplyShopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shop.ReplyShop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string shop_name = 2;</code>
   */
  java.lang.String getShopName();
  /**
   * <code>string shop_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getShopNameBytes();

  /**
   * <code>string api_key = 3;</code>
   */
  java.lang.String getApiKey();
  /**
   * <code>string api_key = 3;</code>
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>string api_key_eff_timlmt = 4;</code>
   */
  java.lang.String getApiKeyEffTimlmt();
  /**
   * <code>string api_key_eff_timlmt = 4;</code>
   */
  com.google.protobuf.ByteString
      getApiKeyEffTimlmtBytes();

  /**
   * <code>int32 api_key_usage_agreement_ver = 5;</code>
   */
  int getApiKeyUsageAgreementVer();

  /**
   * <code>string api_key_usage_agreement_date = 6;</code>
   */
  java.lang.String getApiKeyUsageAgreementDate();
  /**
   * <code>string api_key_usage_agreement_date = 6;</code>
   */
  com.google.protobuf.ByteString
      getApiKeyUsageAgreementDateBytes();

  /**
   * <code>string company_name = 7;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string hojinkaku_name_kbn = 8;</code>
   */
  java.lang.String getHojinkakuNameKbn();
  /**
   * <code>string hojinkaku_name_kbn = 8;</code>
   */
  com.google.protobuf.ByteString
      getHojinkakuNameKbnBytes();

  /**
   * <code>string hojinkaku_posi_kbn = 9;</code>
   */
  java.lang.String getHojinkakuPosiKbn();
  /**
   * <code>string hojinkaku_posi_kbn = 9;</code>
   */
  com.google.protobuf.ByteString
      getHojinkakuPosiKbnBytes();

  /**
   * <code>string rplsnt_kanji_family_name = 10;</code>
   */
  java.lang.String getRplsntKanjiFamilyName();
  /**
   * <code>string rplsnt_kanji_family_name = 10;</code>
   */
  com.google.protobuf.ByteString
      getRplsntKanjiFamilyNameBytes();

  /**
   * <code>string rplsnt_kanji_name = 11;</code>
   */
  java.lang.String getRplsntKanjiName();
  /**
   * <code>string rplsnt_kanji_name = 11;</code>
   */
  com.google.protobuf.ByteString
      getRplsntKanjiNameBytes();

  /**
   * <code>string rplsnt_kana_family_name = 12;</code>
   */
  java.lang.String getRplsntKanaFamilyName();
  /**
   * <code>string rplsnt_kana_family_name = 12;</code>
   */
  com.google.protobuf.ByteString
      getRplsntKanaFamilyNameBytes();

  /**
   * <code>string rplsnt_kana_name = 13;</code>
   */
  java.lang.String getRplsntKanaName();
  /**
   * <code>string rplsnt_kana_name = 13;</code>
   */
  com.google.protobuf.ByteString
      getRplsntKanaNameBytes();

  /**
   * <code>string rplsnt_alphabet_family_name = 14;</code>
   */
  java.lang.String getRplsntAlphabetFamilyName();
  /**
   * <code>string rplsnt_alphabet_family_name = 14;</code>
   */
  com.google.protobuf.ByteString
      getRplsntAlphabetFamilyNameBytes();

  /**
   * <code>string rplsnt_alphabet_name = 15;</code>
   */
  java.lang.String getRplsntAlphabetName();
  /**
   * <code>string rplsnt_alphabet_name = 15;</code>
   */
  com.google.protobuf.ByteString
      getRplsntAlphabetNameBytes();

  /**
   * <code>string store_name = 16;</code>
   */
  java.lang.String getStoreName();
  /**
   * <code>string store_name = 16;</code>
   */
  com.google.protobuf.ByteString
      getStoreNameBytes();

  /**
   * <code>string charge_dept_zip = 17;</code>
   */
  java.lang.String getChargeDeptZip();
  /**
   * <code>string charge_dept_zip = 17;</code>
   */
  com.google.protobuf.ByteString
      getChargeDeptZipBytes();

  /**
   * <code>string charge_dept_address_city = 18;</code>
   */
  java.lang.String getChargeDeptAddressCity();
  /**
   * <code>string charge_dept_address_city = 18;</code>
   */
  com.google.protobuf.ByteString
      getChargeDeptAddressCityBytes();

  /**
   * <code>string charge_dept_address_bldg = 19;</code>
   */
  java.lang.String getChargeDeptAddressBldg();
  /**
   * <code>string charge_dept_address_bldg = 19;</code>
   */
  com.google.protobuf.ByteString
      getChargeDeptAddressBldgBytes();

  /**
   * <code>string charge_dept_name = 20;</code>
   */
  java.lang.String getChargeDeptName();
  /**
   * <code>string charge_dept_name = 20;</code>
   */
  com.google.protobuf.ByteString
      getChargeDeptNameBytes();

  /**
   * <code>string ec_rspsbl_kanji_family_name = 21;</code>
   */
  java.lang.String getEcRspsblKanjiFamilyName();
  /**
   * <code>string ec_rspsbl_kanji_family_name = 21;</code>
   */
  com.google.protobuf.ByteString
      getEcRspsblKanjiFamilyNameBytes();

  /**
   * <code>string ec_rspsbl_kanji_name = 22;</code>
   */
  java.lang.String getEcRspsblKanjiName();
  /**
   * <code>string ec_rspsbl_kanji_name = 22;</code>
   */
  com.google.protobuf.ByteString
      getEcRspsblKanjiNameBytes();

  /**
   * <code>string ec_rspsbl_kana_family_name = 23;</code>
   */
  java.lang.String getEcRspsblKanaFamilyName();
  /**
   * <code>string ec_rspsbl_kana_family_name = 23;</code>
   */
  com.google.protobuf.ByteString
      getEcRspsblKanaFamilyNameBytes();

  /**
   * <code>string ec_rspsbl_kana_name = 24;</code>
   */
  java.lang.String getEcRspsblKanaName();
  /**
   * <code>string ec_rspsbl_kana_name = 24;</code>
   */
  com.google.protobuf.ByteString
      getEcRspsblKanaNameBytes();

  /**
   * <code>string chareg_email_local = 25;</code>
   */
  java.lang.String getCharegEmailLocal();
  /**
   * <code>string chareg_email_local = 25;</code>
   */
  com.google.protobuf.ByteString
      getCharegEmailLocalBytes();

  /**
   * <code>string charge_email_domain = 26;</code>
   */
  java.lang.String getChargeEmailDomain();
  /**
   * <code>string charge_email_domain = 26;</code>
   */
  com.google.protobuf.ByteString
      getChargeEmailDomainBytes();

  /**
   * <code>string user_contact_email_local = 27;</code>
   */
  java.lang.String getUserContactEmailLocal();
  /**
   * <code>string user_contact_email_local = 27;</code>
   */
  com.google.protobuf.ByteString
      getUserContactEmailLocalBytes();

  /**
   * <code>string user_contact_email_domain = 28;</code>
   */
  java.lang.String getUserContactEmailDomain();
  /**
   * <code>string user_contact_email_domain = 28;</code>
   */
  com.google.protobuf.ByteString
      getUserContactEmailDomainBytes();

  /**
   * <code>string adviser_email_local = 29;</code>
   */
  java.lang.String getAdviserEmailLocal();
  /**
   * <code>string adviser_email_local = 29;</code>
   */
  com.google.protobuf.ByteString
      getAdviserEmailLocalBytes();

  /**
   * <code>string adviser_email_domain = 30;</code>
   */
  java.lang.String getAdviserEmailDomain();
  /**
   * <code>string adviser_email_domain = 30;</code>
   */
  com.google.protobuf.ByteString
      getAdviserEmailDomainBytes();

  /**
   * <code>string consumer_contact_tel = 31;</code>
   */
  java.lang.String getConsumerContactTel();
  /**
   * <code>string consumer_contact_tel = 31;</code>
   */
  com.google.protobuf.ByteString
      getConsumerContactTelBytes();

  /**
   * <code>string fax_no = 32;</code>
   */
  java.lang.String getFaxNo();
  /**
   * <code>string fax_no = 32;</code>
   */
  com.google.protobuf.ByteString
      getFaxNoBytes();

  /**
   * <code>string hp_addr = 33;</code>
   */
  java.lang.String getHpAddr();
  /**
   * <code>string hp_addr = 33;</code>
   */
  com.google.protobuf.ByteString
      getHpAddrBytes();

  /**
   * <code>int64 current_user_relation_key = 34;</code>
   */
  long getCurrentUserRelationKey();

  /**
   * <code>string notes = 35;</code>
   */
  java.lang.String getNotes();
  /**
   * <code>string notes = 35;</code>
   */
  com.google.protobuf.ByteString
      getNotesBytes();

  /**
   * <code>int32 del_flg = 36;</code>
   */
  int getDelFlg();

  /**
   * <code>string create_date = 37;</code>
   */
  java.lang.String getCreateDate();
  /**
   * <code>string create_date = 37;</code>
   */
  com.google.protobuf.ByteString
      getCreateDateBytes();

  /**
   * <code>string update_date = 38;</code>
   */
  java.lang.String getUpdateDate();
  /**
   * <code>string update_date = 38;</code>
   */
  com.google.protobuf.ByteString
      getUpdateDateBytes();

  /**
   * <code>int32 create_id = 39;</code>
   */
  int getCreateId();

  /**
   * <code>int32 update_id = 40;</code>
   */
  int getUpdateId();

  /**
   * <code>string create_pgm_id = 41;</code>
   */
  java.lang.String getCreatePgmId();
  /**
   * <code>string create_pgm_id = 41;</code>
   */
  com.google.protobuf.ByteString
      getCreatePgmIdBytes();

  /**
   * <code>string update_pgm_id = 42;</code>
   */
  java.lang.String getUpdatePgmId();
  /**
   * <code>string update_pgm_id = 42;</code>
   */
  com.google.protobuf.ByteString
      getUpdatePgmIdBytes();

  /**
   * <code>int64 version = 43;</code>
   */
  long getVersion();
}
