// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package grpc.shop.proto;

public interface RequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shop.RequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 id = 1;</code>
   */
  java.util.List<java.lang.Long> getIdList();
  /**
   * <code>repeated int64 id = 1;</code>
   */
  int getIdCount();
  /**
   * <code>repeated int64 id = 1;</code>
   */
  long getId(int index);
}
