// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop.proto

package grpc.shop.proto;

public final class ShopProto {
  private ShopProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shop_RequestId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shop_RequestId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shop_ReplyShopList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shop_ReplyShopList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shop_ReplyShop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shop_ReplyShop_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nshop.proto\022\004shop\"\027\n\tRequestId\022\n\n\002id\030\001 " +
      "\003(\003\"7\n\rReplyShopList\022&\n\rreplyShopList\030\001 " +
      "\003(\0132\017.shop.ReplyShop\"\204\t\n\tReplyShop\022\n\n\002id" +
      "\030\001 \001(\003\022\021\n\tshop_name\030\002 \001(\t\022\017\n\007api_key\030\003 \001" +
      "(\t\022\032\n\022api_key_eff_timlmt\030\004 \001(\t\022#\n\033api_ke" +
      "y_usage_agreement_ver\030\005 \001(\005\022$\n\034api_key_u" +
      "sage_agreement_date\030\006 \001(\t\022\024\n\014company_nam" +
      "e\030\007 \001(\t\022\032\n\022hojinkaku_name_kbn\030\010 \001(\t\022\032\n\022h" +
      "ojinkaku_posi_kbn\030\t \001(\t\022 \n\030rplsnt_kanji_" +
      "family_name\030\n \001(\t\022\031\n\021rplsnt_kanji_name\030\013" +
      " \001(\t\022\037\n\027rplsnt_kana_family_name\030\014 \001(\t\022\030\n" +
      "\020rplsnt_kana_name\030\r \001(\t\022#\n\033rplsnt_alphab" +
      "et_family_name\030\016 \001(\t\022\034\n\024rplsnt_alphabet_" +
      "name\030\017 \001(\t\022\022\n\nstore_name\030\020 \001(\t\022\027\n\017charge" +
      "_dept_zip\030\021 \001(\t\022 \n\030charge_dept_address_c" +
      "ity\030\022 \001(\t\022 \n\030charge_dept_address_bldg\030\023 " +
      "\001(\t\022\030\n\020charge_dept_name\030\024 \001(\t\022#\n\033ec_rsps" +
      "bl_kanji_family_name\030\025 \001(\t\022\034\n\024ec_rspsbl_" +
      "kanji_name\030\026 \001(\t\022\"\n\032ec_rspsbl_kana_famil" +
      "y_name\030\027 \001(\t\022\033\n\023ec_rspsbl_kana_name\030\030 \001(" +
      "\t\022\032\n\022chareg_email_local\030\031 \001(\t\022\033\n\023charge_" +
      "email_domain\030\032 \001(\t\022 \n\030user_contact_email" +
      "_local\030\033 \001(\t\022!\n\031user_contact_email_domai" +
      "n\030\034 \001(\t\022\033\n\023adviser_email_local\030\035 \001(\t\022\034\n\024" +
      "adviser_email_domain\030\036 \001(\t\022\034\n\024consumer_c" +
      "ontact_tel\030\037 \001(\t\022\016\n\006fax_no\030  \001(\t\022\017\n\007hp_a" +
      "ddr\030! \001(\t\022!\n\031current_user_relation_key\030\"" +
      " \001(\003\022\r\n\005notes\030# \001(\t\022\017\n\007del_flg\030$ \001(\005\022\023\n\013" +
      "create_date\030% \001(\t\022\023\n\013update_date\030& \001(\t\022\021" +
      "\n\tcreate_id\030\' \001(\005\022\021\n\tupdate_id\030( \001(\005\022\025\n\r" +
      "create_pgm_id\030) \001(\t\022\025\n\rupdate_pgm_id\030* \001" +
      "(\t\022\017\n\007version\030+ \001(\0032=\n\004Shop\0225\n\013GetShopBy" +
      "Id\022\017.shop.RequestId\032\023.shop.ReplyShopList" +
      "\"\000B\036\n\017grpc.shop.protoB\tShopProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_shop_RequestId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shop_RequestId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shop_RequestId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_shop_ReplyShopList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_shop_ReplyShopList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shop_ReplyShopList_descriptor,
        new java.lang.String[] { "ReplyShopList", });
    internal_static_shop_ReplyShop_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_shop_ReplyShop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shop_ReplyShop_descriptor,
        new java.lang.String[] { "Id", "ShopName", "ApiKey", "ApiKeyEffTimlmt", "ApiKeyUsageAgreementVer", "ApiKeyUsageAgreementDate", "CompanyName", "HojinkakuNameKbn", "HojinkakuPosiKbn", "RplsntKanjiFamilyName", "RplsntKanjiName", "RplsntKanaFamilyName", "RplsntKanaName", "RplsntAlphabetFamilyName", "RplsntAlphabetName", "StoreName", "ChargeDeptZip", "ChargeDeptAddressCity", "ChargeDeptAddressBldg", "ChargeDeptName", "EcRspsblKanjiFamilyName", "EcRspsblKanjiName", "EcRspsblKanaFamilyName", "EcRspsblKanaName", "CharegEmailLocal", "ChargeEmailDomain", "UserContactEmailLocal", "UserContactEmailDomain", "AdviserEmailLocal", "AdviserEmailDomain", "ConsumerContactTel", "FaxNo", "HpAddr", "CurrentUserRelationKey", "Notes", "DelFlg", "CreateDate", "UpdateDate", "CreateId", "UpdateId", "CreatePgmId", "UpdatePgmId", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
